services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: namadesa
      MYSQL_ROOT_PASSWORD: rahasia
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  db_data:
