# Generated by Django 5.2.4 on 2025-07-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('kode_desa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('kode_kabupaten', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('kode_kecamatan', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('kode_provinsi', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DomainDesa',
            fields=[
                ('kode_domain', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nama_domain', models.CharField(max_length=250)),
                ('kode_desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.desa')),
                ('kode_kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.kabupaten')),
                ('kode_kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.kecamatan')),
                ('kode_provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekomendasi.provinsi')),
            ],
        ),
    ]
