# Generated by Django 5.2.4 on 2025-07-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaindesa',
            name='kode_domain',
        ),
        migrations.AddField(
            model_name='domaindesa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
